ALTER TYPE lead_classificacao RENAME VALUE 'QUENTE' TO 'HOT';
ALTER TYPE lead_classificacao RENAME VALUE 'MORNO' TO 'WARM';
ALTER TYPE lead_classificacao RENAME VALUE 'FRIO' TO 'COLD';
ALTER TYPE lead_classificacao RENAME VALUE 'DESQUALIFICADO' TO 'DISQUALIFIED';
